import { Metadata } from 'next';
import Breadcrumbs from '@/components/ui/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description:
    'Terms of use for HOOKED. Read our terms and conditions before using the site.',
  alternates: { canonical: 'https://hookedguide.com/terms' },
  openGraph: {
    title: 'Terms of Use',
    description: 'Terms of use for HOOKED.',
    url: 'https://hookedguide.com/terms',
  },
  twitter: {
    title: 'Terms of Use',
    description: 'Terms of use for HOOKED.',
  },
};

export default function TermsOfUsePage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12">
      <Breadcrumbs
        items={[
          { label: 'Home', href: '/' },
          { label: 'Terms' },
        ]}
      />

      <h1 className="font-heading text-3xl font-bold text-water-900 dark:text-sand-50 mt-4 mb-2">
        Terms of Use
      </h1>
      <p className="text-sm text-water-500 dark:text-sand-400 mb-8">
        Last updated: April 2026
      </p>

      {/* Acceptance of Terms */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Acceptance of Terms
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          By accessing and using HookedGuide (&quot;the Site&quot;), you accept
          and agree to be bound by these Terms of Use. If you do not agree to
          these terms, please do not use the Site. We reserve the right to modify
          these terms at any time, and your continued use of the Site
          constitutes acceptance of any changes.
        </p>
      </section>

      {/* Use of Service */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Use of Service
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          HookedGuide provides fishing-related information, recommendations,
          guides, and product links for informational and educational purposes.
          You agree to use the Site only for lawful purposes and in accordance
          with these Terms. You may not use the Site in any way that could
          damage, disable, or impair the Site or interfere with any other
          party&apos;s use of the Site.
        </p>
      </section>

      {/* Fishing Regulations Disclaimer */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Fishing Regulations Disclaimer
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          The fishing regulations displayed on HookedGuide are provided for
          informational purposes only and may be outdated, incomplete, or
          inaccurate. Always verify current regulations with your state&apos;s
          official fish and wildlife agency before fishing. HookedGuide is not
          responsible for any fines, penalties, or legal issues resulting from
          reliance on regulation information displayed on this site.
        </p>
      </section>

      {/* Recommendation Disclaimer */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Recommendation Disclaimer
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          Our fishing recommendations are generated by a rule-based engine and
          are intended as suggestions only. Fishing success depends on many
          factors beyond our control. We make no guarantees regarding the
          accuracy or effectiveness of any recommendation.
        </p>
      </section>

      {/* Affiliate Disclosure Reference */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Affiliate Disclosure
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          Some links on this site are affiliate links. See our full{' '}
          <a
            href="/disclosure"
            className="text-water-500 dark:text-water-300 underline hover:text-water-600 dark:hover:text-water-200"
          >
            Affiliate Disclosure
          </a>{' '}
          for details.
        </p>
      </section>

      {/* Intellectual Property */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Intellectual Property
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          All content on HookedGuide, including text, graphics, logos, images,
          and software, is the property of HookedGuide or its content suppliers
          and is protected by United States and international copyright laws.
          You may not reproduce, distribute, modify, or create derivative works
          from any content on this Site without prior written consent.
        </p>
      </section>

      {/* Limitation of Liability */}
      <section className="mb-8">
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Limitation of Liability
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          HookedGuide and its operators shall not be liable for any direct,
          indirect, incidental, special, consequential, or punitive damages
          arising out of your access to or use of the Site. This includes,
          without limitation, any errors or omissions in content, any loss or
          damage incurred as a result of the use of any content posted,
          transmitted, or otherwise made available through the Site, even if
          advised of the possibility of such damages.
        </p>
      </section>

      {/* Contact */}
      <section>
        <h2 className="font-heading text-2xl font-semibold text-water-900 dark:text-sand-50 mt-8 mb-4">
          Contact
        </h2>
        <p className="text-water-700 dark:text-sand-200 leading-relaxed">
          If you have any questions about these Terms of Use, please contact us
          at{' '}
          <a
            href="mailto:contact@hookedguide.com"
            className="text-water-500 dark:text-water-300 underline hover:text-water-600 dark:hover:text-water-200"
          >
            contact@hookedguide.com
          </a>
        </p>
      </section>
    </main>
  );
}
